version: "3.3"

services:

  youtrack:
    build: .
    image: pedrocx486/youtrack
    container_name: "youtrack"
    ports:
      - "8080:8080"
    networks:
      - external_network
    volumes:
      - ./data:/opt/youtrack/teamsysdata
      - ./conf:/opt/youtrack/teamsysdata/conf
      - ./backups:/opt/youtrack/.youtrack/backups
      - ./logs:/opt/youtrack/.youtrack/logs

networks:
  external_network:
    external: true
